import { InfoModel } from 'src/app/shared/models';

export const infoDataTransparency: InfoModel[][] = [
  [ new InfoModel('Marco Legal de Transparencia', 'main', 'home', 'primary'),
    new InfoModel('Responsables del acceso a la información pública y PTE', 'main/document', 'person', 'warn'),
    new InfoModel('Formato para acceso a la información pública'),
    new InfoModel('Solicitud electrónica de acceso a la información pública'),
    new InfoModel('Planeamiento y Organización'),
    new InfoModel('Información Presupuestal'),
    new InfoModel('Proyectos de Invesión'),
    new InfoModel('Participación Ciudadana'),
    new InfoModel('Información de Personal'),
    new InfoModel('Información de Contrataciones'),
  ],
  [ new InfoModel('Organigrama', 'main/page', 'book', 'accent'),
  new InfoModel('PDRC', 'main/page', 'book', 'accent'),
    new InfoModel('PEI', 'main/page', 'book', 'accent'),
    new InfoModel('POI', 'main/page', 'book', 'accent'),
    new InfoModel('MOF', 'main/page', 'book', 'accent'),
    new InfoModel('ROF', 'main/page', 'book', 'accent'),
    new InfoModel('CAP', 'main/page', 'book', 'accent'),
    new InfoModel('PAP', 'main/page', 'book', ''),
    new InfoModel('RIC', 'main/page', 'book', 'accent'),
    new InfoModel('TUPA', 'main/page', 'book', 'accent'),
    new InfoModel('MAPRO', 'main/page', 'book', 'accent'),
    new InfoModel('RIT', 'main/page', 'book', 'accent'),
    new InfoModel('PAC', 'main/page', 'book', 'accent'),
    new InfoModel('POIN', 'main/page', 'book', 'accent'),
  ],
  [ new InfoModel('Ley 27867'),
    new InfoModel('Ordenanzas Regionales'),
    new InfoModel('Decretos Regionales'),
    new InfoModel('Resoluciones Ejecutivas Regionales'),
    new InfoModel('Resoluciones Directorales Administrativas'),
    new InfoModel('Resoluciones Subdirectorales Administrativas'),
    new InfoModel('Directivas Regionales'),
    new InfoModel('Convenios y Adendas'),
  ],
  [ new InfoModel('Resoluciones Gerenciales Generales'),
    new InfoModel('Resoluciones Gerenciales Regionales de Infraestructura'),
    new InfoModel('Resoluciones Gerenciales Regionales de Desarrollo Ecónomico'),
    new InfoModel('Resoluciones Gerenciales Regionales de Desarrollo Social'),
    new InfoModel('Resoluciones Gerenciales Regionales de Recursos Naturales y Gestión del Medio Ambiente'),
    new InfoModel('Resoluciones Gerenciales Regionales de Planeamiento, Presupuesto y A.T.'),
    new InfoModel('Resoluciones Directorales'),
    new InfoModel('Otras Resoluciones'),
  ],
  [ new InfoModel('Directorio Regional'),
  new InfoModel('Agendas'),
    new InfoModel('Presupuesto Participativo'),
    new InfoModel('CONCOREJ'),
    new InfoModel('Audiencias Públicas'),
    new InfoModel('Informes de Auditoría'),
    new InfoModel('Memoria Anual'),
    new InfoModel('Declaraciones Juradas de Bienes y Rentas'),
    new InfoModel('Libro de Reclamaciones Eletrónico'),
  ],
];
