import { InfoModel } from '../../../../shared/models';

export const infoDataTransparency: InfoModel[][] = [
  [ new InfoModel('Marco Legal de Transparencia', 'main/group/documents/legal-framework', 'home', 'primary'),
    new InfoModel('Responsables del acceso a la información pública y PTE', 'main/document', 'person', 'warn'),
    new InfoModel('Formato para acceso a la información pública'),
    new InfoModel('Solicitud electrónica de acceso a la información pública'),
    new InfoModel('Planeamiento y Organización'),
    new InfoModel('Información Presupuestal'),
    new InfoModel('Proyectos de Invesión'),
    new InfoModel('Participación Ciudadana'),
    new InfoModel('Información de Personal'),
    new InfoModel('Información de Contrataciones'),
  ],
  [ new InfoModel('Organigrama', 'main/group/documents/development-plan', 'book', 'accent'),
    new InfoModel('PDMC', 'main/group/documents/development-plan', 'book', 'accent'),
    new InfoModel('PEI', 'main/group/documents/strategic-plan', 'book', 'accent'),
    new InfoModel('POI', 'main/group/documents/operational-plan', 'book', 'accent'),
    new InfoModel('MOF', 'main/group/documents/organizations-functions-manual', 'book', 'accent'),
    new InfoModel('ROF', 'main/group/documents/organizations-functions-regulation', 'book', 'accent'),
    new InfoModel('CAP', 'main/group/documents/staff-assignment-chart', 'book', 'accent'),
    new InfoModel('PAP', 'main/group/documents/staff-assignment-chart', 'book', ''),
    new InfoModel('RIC', 'main/group/documents/internal-council-regulation', 'book', 'accent'),
    new InfoModel('TUPA', 'main/group/documents/administrative-processes', 'book', 'accent'),
    new InfoModel('MAPRO', 'main/group/documents/administrative-processes', 'book', 'accent'),
    new InfoModel('RIT', 'main/group/documents/internal-regulations', 'book', 'accent'),
    new InfoModel('PAC', 'main/group/documents/annual-hiring-plan', 'book', 'accent'),
    new InfoModel('POIN', 'main/group/documents/computer-operating-plan', 'book', 'accent'),
  ],
  [ new InfoModel('Ley 27867', 'main/group/documents/ordinances', 'person', 'primary'),
    new InfoModel('Ordenanzas Municipales', 'main/group/documents/ordinances', 'person', 'primary'),
    new InfoModel('Decretos Municipales', 'main/group/documents/decrees', 'person', 'primary'),
    new InfoModel('Resoluciones Ejecutivas Municipales', 'main/group/documents/execute-resolutions', 'person', 'primary'),
    new InfoModel('Resoluciones Directorales Administrativas',
      'main/group/documents/administrative-director-resolution', 'person', 'primary'),
    new InfoModel('Resoluciones Subdirectorales Administrativas',
      'main/group/documents/administrative-subexecutive-resolutions', 'person', 'primary'),
    new InfoModel('Directivas Municipales',
      'main/group/documents/directives', 'person', 'primary'),
    new InfoModel('Convenios y Adendas',
      'main/group/documents/agreements-addenda', 'person', 'primary'),
  ],
  [ new InfoModel('Resoluciones Gerenciales Generales',
      'main/group/documents/general', 'person', 'primary'),
    new InfoModel('Resoluciones Gerenciales Municipales de Infraestructura',
      'main/group/documents/infrastructure', 'person', 'primary'),
    new InfoModel('Resoluciones Gerenciales Municipales de Desarrollo Ecónomico',
      'main/group/documents/economic-development', 'person', 'primary'),
    new InfoModel('Resoluciones Gerenciales Municipales de Desarrollo Social',
      'main/group/documents/social-development', 'person', 'primary'),
    new InfoModel(
      'Resoluciones Gerenciales Municipales de Recursos Naturales y Gestión del Medio Ambiente',
      'main/group/documents/natural-resources', 'person', 'primary'),
    new InfoModel('Resoluciones Gerenciales Municipales de Planeamiento, Presupuesto y A.T.',
      'main/group/documents/planning-budget', 'person', 'primary'),
    new InfoModel('Resoluciones Directorales',
      'main/group/documents/directors', 'person', 'primary'),
    new InfoModel('Otras Resoluciones',
      'main/group/documents/other-resolutions', 'person', 'primary'),
  ],
  [ new InfoModel('Directorio Regional',
      'main/group/documents/coordination-council', 'person', 'primary'),
    new InfoModel('Agendas',
      'main/group/documents/coordination-council', 'person', 'primary'),
    new InfoModel('Presupuesto Participativo',
      'main/group/documents/coordination-council', 'person', 'primary'),
    new InfoModel('CONCOREJ',
      'main/group/documents/coordination-council', 'person', 'primary'),
    new InfoModel('Audiencias Públicas',
      'main/group/documents/coordination-council', 'person', 'primary'),
    new InfoModel('Informes de Auditoría',
      'main/group/documents/audit-reports', 'person', 'primary'),
    new InfoModel('Memoria Anual',
      'main/group/documents/annual-reports', 'person', 'primary'),
    new InfoModel('Declaraciones Juradas de Bienes y Rentas',
      'main/group/documents/annual-reports', 'person', 'primary'),
    new InfoModel('Libro de Reclamaciones Eletrónico',
      'main/group/documents/annual-reports', 'person', 'primary'),
  ],
];
