import { InfoModel } from '../../../../shared/models';

export const infoDataTransparency: InfoModel[][] = [
  [ new InfoModel('Marco Legal de Transparencia', 'main/group/documents/legal-framework', 'home', 'accent'),
    new InfoModel('Responsables del acceso a la información pública y PTE', 'main/document', 'person', 'accent'),
    new InfoModel('Formato para acceso a la información pública', 'main/group/documents/public-information', 'book', 'accent'),
    new InfoModel('Solicitud electrónica de acceso a la información pública', 'main/group/documents/public-information', 'book', 'accent'),
    new InfoModel('Planeamiento y Organización', 'main/group/documents/public-information', 'book', 'accent'),
    new InfoModel('Información Presupuestal', 'main/group/documents/public-information', 'book', 'accent'),
    new InfoModel('Proyectos de Invesión', 'main/group/documents/public-information', 'book', 'accent'),
    new InfoModel('Participación Ciudadana', 'main/group/documents/public-information', 'book', 'accent'),
    new InfoModel('Información de Personal', 'main/group/documents/public-information', 'book', 'accent'),
    new InfoModel('Información de Contrataciones', 'main/group/documents/public-information', 'book', 'accent'),
  ],
  [ new InfoModel('Organigrama', 'main/group/documents/organization-chart', 'book', 'accent'),
    new InfoModel('PDMC', 'main/group/documents/development-plan', 'book', 'accent'),
    new InfoModel('PEI', 'main/group/documents/strategic-plan', 'book', 'accent'),
    new InfoModel('POI', 'main/group/documents/operational-plan', 'book', 'accent'),
    new InfoModel('MOF', 'main/group/documents/organizations-functions-manual', 'book', 'accent'),
    new InfoModel('ROF', 'main/group/documents/organizations-functions-regulation', 'book', 'accent'),
    new InfoModel('CAP', 'main/group/documents/staff-assignment-chart', 'book', 'accent'),
    new InfoModel('PAP', 'main/group/documents/staff-analytical-budget', 'book', 'accent'),
    new InfoModel('RIC', 'main/group/documents/internal-council-regulation', 'book', 'primary'),
    new InfoModel('TUPA', 'main/group/documents/utap', 'book', 'primary'),
    new InfoModel('MAPRO', 'main/group/documents/administrative-processes', 'book', 'accent'),
    new InfoModel('RIT', 'main/group/documents/internal-regulations', 'book', 'accent'),
    new InfoModel('PAC', 'main/group/documents/annual-hiring-plan', 'book', 'accent'),
    new InfoModel('POIN', 'main/group/documents/computer-operating-plan', 'book', 'accent'),
    new InfoModel('RASA', 'main/group/documents/rasa', 'book', 'primary'),
    new InfoModel('CUIS', 'main/group/documents/cuis', 'book', 'primary'),
  ],
  [ new InfoModel('Ley 27867', 'main/group/documents/organic-law', 'person', 'accent'),
    new InfoModel('Ordenanzas Municipales', 'main/group/documents/ordinances', 'person', 'accent'),
    new InfoModel('Decretos Municipales', 'main/group/documents/decrees', 'person', 'accent'),
    new InfoModel('Resoluciones Ejecutivas Municipales', 'main/group/documents/execute-resolutions', 'person', 'accent'),
    new InfoModel('Resoluciones Directorales Administrativas',
      'main/group/documents/administrative-director-resolution', 'person', 'accent'),
    new InfoModel('Resoluciones Subdirectorales Administrativas',
      'main/group/documents/administrative-subexecutive-resolutions', 'person', 'accent'),
    new InfoModel('Directivas Municipales',
      'main/group/documents/directives', 'person', 'accent'),
    new InfoModel('Convenios y Adendas',
      'main/group/documents/agreements-addenda', 'person', 'accent'),
  ],
  [ new InfoModel('Resoluciones Gerenciales Generales',
      'main/group/documents/general', 'person', 'accent'),
    new InfoModel('Resoluciones Gerenciales Municipales de Infraestructura',
      'main/group/documents/infrastructure', 'person', 'accent'),
    new InfoModel('Resoluciones Gerenciales Municipales de Desarrollo Ecónomico',
      'main/group/documents/economic-development', 'person', 'accent'),
    new InfoModel('Resoluciones Gerenciales Municipales de Desarrollo Social',
      'main/group/documents/social-development', 'person', 'accent'),
    new InfoModel(
      'Resoluciones Gerenciales Municipales de Recursos Naturales y Gestión del Medio Ambiente',
      'main/group/documents/natural-resources', 'person', 'accent'),
    new InfoModel('Resoluciones Gerenciales Municipales de Planeamiento, Presupuesto y A.T.',
      'main/group/documents/planning-budget', 'person', 'accent'),
    new InfoModel('Resoluciones Directorales',
      'main/group/documents/directors', 'person', 'accent'),
    new InfoModel('Otras Resoluciones',
      'main/group/documents/other-resolutions', 'person', 'accent'),
  ],
  [ new InfoModel('Directorio Muncipal',
      'main/group/documents/coordination-council', 'person', 'accent'),
    new InfoModel('Agendas',
      'main/group/documents/coordination-council', 'person', 'accent'),
    new InfoModel('Presupuesto Participativo',
      'main/group/documents/participatory-budget', 'person', 'accent'),
    new InfoModel('CONCOMUN',
      'main/group/documents/coordination-council', 'person', 'accent'),
    new InfoModel('Audiencias Públicas',
      'main/group/documents/public audiences', 'person', 'accent'),
    new InfoModel('Informes de Auditoría',
      'main/group/documents/audit-reports', 'person', 'accent'),
    new InfoModel('Memoria Anual',
      'main/group/documents/annual-reports', 'person', 'accent'),
    new InfoModel('Declaraciones Juradas de Bienes y Rentas',
      'main/group/documents/assets-income-affidavit', 'person', 'accent'),
    new InfoModel('Libro de Reclamaciones Eletrónico',
      'main/group/documents/annual-reports', 'person', 'accent'),
  ],
];
